version: '3.9'

services:
    
    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/html
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - app
        volumes:
            ###> NGINX VOLUMES
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/html
        networks:
            - reverse-proxy
            - backend
    
    app:
        build:
            context: ./app
            args:
                NODE: ${NODE_VERSION}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-app
        working_dir: /var/www/html
        stdin_open: true
        tty: true
        ports:
            - "3000:3000"
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bash_history:/root/.bash_history
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/html
        command: sh -c "npm i; npm run dev"
        networks:
            - backend
        extra_hosts:
            - api.pdf.local:${DOCKER_IP}

networks:
    reverse-proxy:
        name: ${PROXY_NETWORK_NAME:-docker_engine_reverse_proxy}
        external: true
        
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network