apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ .Chart.Name }}-certificate
spec:
    secretName: {{ .Chart.Name }}-tls
    renewBefore: 240h
    duration: 2160h
    commonName: {{ .Values.host }}
    dnsNames:
        - {{ .Values.host }}
    issuerRef:
        name: {{ .Chart.Name }}-letsencrypt
        kind: ClusterIssuer