apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
      kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdf-frontend-app-service
                port:
                  number: {{ .Values.port }}
  tls:
      - hosts:
          - {{ .Values.host }}
        secretName: {{ .Chart.Name }}-tls
